version: "3"
services:
  mocrat-nginx:
      image: nginx:alpine
      container_name: mocrat-nginx
      ports:
        - "8080:8080"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        # - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./mocrat_app/static:/static
      depends_on:
        - mocrat-app

  mocrat-app:
    build:
      context: ./mocrat_app
      dockerfile: Dockerfile
    # Django の Header Error 回避のためアンダーバー使用禁止
    container_name: mocrat-app
    volumes:
      - ./mocrat_app:/usr/mocrat/app
    expose:
      - "8001"
    tty: true
    stdin_open: true
    command: uwsgi --socket :8001 --module mocrat_config.wsgi --processes 2
    depends_on:
        - mocrat_db
    
  mocrat_db:
    build:
      context: ./mocrat_db
      dockerfile: Dockerfile
    container_name: mocrat_db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./mocrat_db/data:/var/lib/postgresql/data

  discord_app:
    build:
      context: ./discord_app
      dockerfile: Dockerfile
    container_name: discord_app
    volumes:
      - ./discord_app:/usr/app
    tty: true
    stdin_open: true
    command: python src/discord_bot.py